import Head from "next/head";
import ProductCard from "../../components/ProductCard";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "./CSRPage.module.css";

const CSRPage = () => {
  const [products, setProducts] = useState(null);

  useEffect(() => {
    async function fetchProducts() {
      const res = await fetch(`http://localhost:4000/products`);
      console.log(process.env.DB_HOST);
      setProducts(await res.json());
    }
    fetchProducts();
  }, []);

  if (!products) return null;

  return (
    <div className={styles.container}>
      <Head>
        <title>CSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Client Side Rendering</h1>
      <div className={styles.productsContainer}>
        {products.map(({ id, name, price, imageSrc }) => (
          <Link key={id} href={`/products-csr/${id}`}>
            <a>
              <ProductCard name={name} price={price} imageSrc={imageSrc} />
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default CSRPage;
