import Head from "next/head";
import ProductCard from "../../components/ProductCard";
import Link from "next/link";
import styles from "./SSRPage.module.css";

export async function getServerSideProps({ params }) {
  const res = await fetch(`${process.env.DB_HOST}/products`);
  const products = await res.json();
  return {
    props: {
      products,
    },
  };
}

const SSRPage = ({ products }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Server Side Rendering</h1>
      <div className={styles.productsContainer}>
        {products.map(({ id, name, price, imageSrc }) => (
          <Link key={id} href={`/products-ssr/${id}`}>
            <a>
              <ProductCard name={name} price={price} imageSrc={imageSrc} />
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default SSRPage;
