import type { NextPage } from "next";
import Head from "next/head";
import ProductCard from "../components/ProductCard";
import Link from "next/link";
import styles from "./Home.module.css";

export async function getStaticProps() {
  const res = await fetch("http://localhost:4000/products?_page=1&_limit=3");
  const featuredProducts = await res.json();
  return {
    props: {
      featuredProducts,
    },
  };
}

const Home: NextPage = ({ featuredProducts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.pageTypeRow}>
        <h1> Client side rendered pages </h1>
        <div className={styles.productCardRow}>
          {featuredProducts.map(({ id, name, price, imageSrc }) => (
            <Link key={id} href={`/products-csr/${id}`}>
              <a>
                <ProductCard name={name} price={price} imageSrc={imageSrc} />
              </a>
            </Link>
          ))}
        </div>
      </div>
      <div className={styles.pageTypeRow}>
        <h1> Server side rendered pages </h1>
        <div className={styles.productCardRow}>
          {featuredProducts.map(({ id, name, price, imageSrc }) => (
            <Link key={id} href={`/products-ssr/${id}`}>
              <a>
                <ProductCard name={name} price={price} imageSrc={imageSrc} />
              </a>
            </Link>
          ))}
        </div>
      </div>
      <div className={styles.pageTypeRow}>
        <h1> Statically generated pages (with ISR) </h1>
        <div className={styles.productCardRow}>
          {featuredProducts.map(({ id, name, price, imageSrc }) => (
            <Link key={id} href={`/products-ssg/${id}`}>
              <a>
                <ProductCard name={name} price={price} imageSrc={imageSrc} />
              </a>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Home;
